encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.get_title, name="title"),
    path("wiki/search/", views.search, name="search"),
    path("random/", views.random, name="random"),
    path("wiki/create/", views.create, name="add"),
    path("wiki/edit/", views.edit, name="edit"),
    path("wiki/save/", views.save, name="save")

    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from . import util
from django.http import HttpResponseRedirect
import re
import markdown2
from markdown2 import Markdown
from random import choice
from django import forms


markdowner = Markdown()

class NewAddForm(forms.Form):
    title = forms.CharField(label= "Title", required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label="New Entry", required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))

class Edit(forms.Form):
    title = forms.CharField(label= "Title", required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(label="Edit Content", required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        
    })

def get_title(request, title):
    markdowner = Markdown()
    entries = util.list_entries()

    if title in entries:
        page = util.get_entry(title)
        markdowner = markdowner.convert(page)
        return render(request, "encyclopedia/pagetitle.html",{
            "page": markdowner,
            "title": title
        })
    else:
        return render(request, "encyclopedia/404Error.html",{
            "page": title
        })

def search(request):
    if request.method == "GET":
        query = request.GET["q"]
        entry = util.get_entry(query)
        
        if entry:
            page = markdown2.markdown(util.get_entry(query))
            return render(request, "encyclopedia/pagetitle.html",{
                "title": query,
                "page": page
            })

        else:
            entries = util.list_entries()
            substring = []
            for entry1 in entries:
                print(entry1)
                if re.search(query, entry1, re.IGNORECASE):
                    substring.append(entry1)
                    print(substring)
                    
            if substring:
                return render(request, "encyclopedia/index.html",{
                    "entries":substring
                })
            else:
                return render(request, "encyclopedia/404Error.html",{
                    "page": query
                })

def random(request):
    return get_title(request,choice(util.list_entries()))

def create(request):
    if request.method == "POST":
            form = NewAddForm(request.POST)

            if form.is_valid():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
                entries1 = util.list_entries()
                for name in entries1:
                    if title.lower() == name.lower() or title.upper() == name.upper():
                        message = "Page exists with title '%s'" %name
                        return render(request, "encyclopedia/new.html",{
                            "form": form,
                            "error": message
                        })
                        
                
                if util.get_entry(title) is None:
                    util.save_entry(title,content)
                    return HttpResponseRedirect(reverse("wiki:index"))
    else:
        if request.method == "GET":
            return render(request,"encyclopedia/new.html",{
                "form": NewAddForm()
            })

def edit(request):
    title = request.POST.get("edit")
    content = util.get_entry(title)
    

    form_edit = Edit(initial={'title':title,'content':content})
    
    if form_edit.is_valid():

        return render(request, "encyclopedia/edit.html",{
            "title":title,
            "form_edit": form_edit
        })
    else:
        return render(request, "encyclopedia/edit.html",{
            "title":title,
            "form_edit": form_edit
        })


def save(request):

    form_edit = Edit(request.POST)
    
    if form_edit.is_valid():
        title = form_edit.cleaned_data["title"]
        content = form_edit.cleaned_data["content"]
        

        util.save_entry(title,content)
        converted = markdowner.convert(content)
        return render(request,"encyclopedia/pagetitle.html",{
                'page': converted,
                'title': title
            })
    else:
        return render(request, "encyclopedia/edit.html",{
            "title":title,
            "form_edit": form_edit
        })

    


                
  
            


             


            
                



      

        
       

encyclopedia/templates/encyclopedia/404Error.html
{%extends "encyclopedia/layout.html"%}

{%block title%}
    encyclopedia
{%endblock%}

{%block body%}
<h1>Error 404: {{page}} not  found!</h1>
{%endblock%}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>Edit entry</h1>
<div >
    <form action="{% url 'wiki:save' %}" method="POST">
        <div>
            {% csrf_token %}
            {{ form_edit }}
        </div>
       <div style="margin: 10px;"> 
        <button type="submit">Save</button>
       </div>
    </form>
</div>



{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1 class="text-align-pages">Welcome to Encyclopedia Pages</h1>

    <ul class="decoration">
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body class="layout-padding">
        <div class="row" >
            <div class="sidebar col-lg-2 col-md-3">
                <h2 class="text-align-pages">Wiki</h2>
                
                <form action="{% url 'wiki:search' %}" method="GET">
                    <input class="form-padding" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <br/>
                <div>
                    <div>
                        <a href="{% url 'wiki:index' %}">Home</a>
                    </div>
    
                    <div>
                        <a href="{% url 'wiki:add' %}">Create New Page</a>
                    </div>
    
                    <div>
                        <a href="{% url 'wiki:random' %}">Random Page</a> 
                    </div>
                </div>
                

                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create Content
{% endblock %}
{% block body %}
<div>
    <h1>Create a New Page</h1>
</div>

<h4>
    {{error}}
</h4>
    
<div >
    <form action="{% url 'wiki:add' %}" method="POST">
        <div>
            {% csrf_token %}
            {{ form }}
        </div>
       <div style="margin: 10px;"> 
        <button type="submit">Save</button>
       </div>
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/pagetitle.html
{% extends "encyclopedia/layout.html" %}

{%block title%}
    {{ title }}
{%endblock%}


{%block body%}
<h1>{{title}}</h1>
{{page|safe}}
    <form action="{% url 'wiki:edit' %}" method="POST">
        <button type="submit" name="edit" value="{{title}}" id="edit">edit</button>

        {% csrf_token %}
        
    </form>

{%endblock%}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{%block title%}
    Encyclopedia
{%endblock%}

{%block body%}
    <h1>Search results for '{{query}}'</h1>
    <hr>

        <ul>
            {%for substring in substrings%}
                <li><a href="{%url 'wiki:title' title=substring%}">{{substring}}</a></li>
            {% endfor%}
        </ul>

{%endblock%}